spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vpn_bot
    username: vpn_user
    password: vpn_pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      password: ${REDIS_PASSWORD:supersecret123}
      timeout: 2s
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.boot.context.config: DEBUG

app:
  rate-limit:
    window-seconds: 3
    max-requests: 3
  idempotency:
    ttl-seconds: 10
    update-ttl-seconds: 600

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
  admin-ids: "980389038,592239190"
  main-menu-text: |-
    –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å –≤ REDCastle! üè∞‚ú®

    REDCastle ‚Äî –ø–µ—Ä—Å–æ–Ω–∞–ª—å–Ω—ã–π –¥–æ—Å—Ç—É–ø –∫ –ø—Ä–∏–≤–∞—Ç–Ω–æ–º—É –∫–∞–Ω–∞–ª—É –∏ —Å–µ—Ä–≤–∏—Å–∞–º.
    –†–∞–±–æ—Ç–∞–µ—Ç –ø–æ –∫–ª—é—á—É, –∫–æ—Ç–æ—Ä—ã–π –≤—ã –ø–æ–ª—É—á–∞–µ—Ç–µ –∑–¥–µ—Å—å.

    –í—ã–±–µ—Ä–∏—Ç–µ —Ä–∞–∑–¥–µ–ª –Ω–∏–∂–µ. üëá

  instructions-text: |-
    üìå –ò–Ω—Å—Ç—Ä—É–∫—Ü–∏—è –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è

    üí° –ö–ª—é—á –Ω–∞—á–∏–Ω–∞–µ—Ç—Å—è —Å vless:// ‚Äî –ø—Ä–æ—Å—Ç–æ —Å–∫–æ–ø–∏—Ä—É–π—Ç–µ –µ–≥–æ.

    üì± iPhone (v2rayTun):
    1) –°–∫–æ–ø–∏—Ä—É–π—Ç–µ –∫–ª—é—á
    2) –û—Ç–∫—Ä–æ–π—Ç–µ v2rayTun ‚Üí + ‚Üí Import from Clipboard
    3) –°–æ—Ö—Ä–∞–Ω–∏—Ç–µ –∏ –≤–∫–ª—é—á–∏—Ç–µ

    ü§ñ Android (Happ):
    1) –°–∫–æ–ø–∏—Ä—É–π—Ç–µ –∫–ª—é—á
    2) –û—Ç–∫—Ä–æ–π—Ç–µ Happ ‚Üí –î–æ–±–∞–≤–∏—Ç—å/–ò–º–ø–æ—Ä—Ç ‚Üí –ò–∑ –±—É—Ñ–µ—Ä–∞ –æ–±–º–µ–Ω–∞
    3) –°–æ—Ö—Ä–∞–Ω–∏—Ç–µ –∏ –≤–∫–ª—é—á–∏—Ç–µ

    –ï—Å–ª–∏ –∏–º–ø–æ—Ä—Ç –Ω–µ –ø–æ—è–≤–∏–ª—Å—è, –≤—Å—Ç–∞–≤—å—Ç–µ –∫–ª—é—á –≤—Ä—É—á–Ω—É—é —á–µ—Ä–µ–∑ ¬´–î–æ–±–∞–≤–∏—Ç—å¬ª.

xui:
  inbound-id: 1
  public-host: 46.226.164.227
  public-port: 443
  link-tag: REDCastle
  # base-url: ${XUI_BASE_URL}
  # base-path: ${XUI_BASE_PATH}
  # username: ${XUI_USERNAME}
  # password: ${XUI_PASSWORD}
  base-url: http://46.226.164.227:8080
  base-path: /hzxIlrhXF2GmPjywyD/
  username: ibragim
  password: xasuev9595

reality-public-key: zaz32XFf8CdLqgjovVymvI0sEEEDr5eS0Gy8Jua8OFQ
